
DEVICE_PATH := device/infinix/x6835b

# إعدادات النواة (حل مشكلة Missing Kernel)
TARGET_NO_KERNEL := false
BOARD_KERNEL_IMAGE_NAME := kernel
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/kernel
BOARD_USES_RECOVERY_AS_BOOT := true

# مواصفات المعالج والهندسة
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_SUPPORTS_64_BIT_APPS := true

# إعدادات الذاكرة والكيرنل (MT6765)
BOARD_KERNEL_PAGESIZE := 2048
BOARD_BOOTIMG_HEADER_VERSION := 2
BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x11080000
BOARD_TAGS_OFFSET := 0x07080000

# إعدادات الشاشة والواجهة
TARGET_SCREEN_HEIGHT := 1640
TARGET_SCREEN_WIDTH := 720
TW_THEME := portrait_hdpi

# إعدادات البناء
BOARD_HAS_NO_SELECT_BUTTON := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
BOARD_RECOVERY_DEVICE_DIRS := $(DEVICE_PATH)
TARGET_RECOVERY_ROOT_OUT := out/target/product/x6835b/recovery/root

BOARD_HAS_NO_REAL_VENDOR_PARTITION := true
BOARD_HAS_NO_REAL_VENDOR_PARTITION := true
