DEVICE_PATH := device/infinix/x6835b
TARGET_BOARD_PLATFORM := mt6765
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
BOARD_KERNEL_PAGESIZE := 2048
BOARD_BOOTIMG_HEADER_VERSION := 2
BOARD_HAS_NO_SELECT_BUTTON := true
